@echo off
echo Starting MongoDB...
net start MongoDB
echo Starting Backend...
start cmd /k "cd /d %~dp0backend && node server.js"
echo Starting Frontend...
start cmd /k "cd /d %~dp0 && npm run dev"
echo Project is starting...
echo Open http://localhost:8080 in your browser
pause
