/**
 * asim saeed"i am working on database
 * User Model - FaceGate Authentication System
 * Author: Asim Saeed - Database Engineer
 * Date: April 2026
 *
 * This model defines the MongoDB schema for storing user registration data
 * including facial descriptors for passwordless biometric authentication.
 *
 * Security Note: Raw face images are NEVER stored. Only 128-dimensional
 * float descriptor arrays are persisted to protect user biometric privacy.
 * A face descriptor cannot be reverse-engineered back into a face image.
 */

const mongoose = require('mongoose');

const UserSchema = new mongoose.Schema({

  // Full name of the registered user
  name: {
    type: String,
    trim: true
  },

  // Unique email address - used as identity key to prevent duplicates
  email: {
    type: String,
    unique: true,
    lowercase: true,
    trim: true
  },

  // Role-based access: 'admin' gets full dashboard, 'user' gets personal dashboard
  role: {
    type: String,
    enum: ['admin', 'user'],
    default: 'user'
  },

  /**
   * Face Descriptor Array (Core Biometric Identifier)
   *
   * Generated by face-api.js using FaceRecognitionNet model.
   * Contains exactly 128 float values representing unique facial geometry.
   * During login, Euclidean distance between stored and live descriptor
   * is calculated. If distance < 0.3, the user is authenticated.
   *
   * Security: This is a one-way mathematical representation.
   * It cannot be converted back to a face image.
   */
  faceDescriptor: {
    type: [Number],
    validate: {
      validator: function(arr) {
        return arr && arr.length === 128;
      },
      message: 'Face descriptor must contain exactly 128 float values'
    }
  },

  // Timestamp of registration for audit trail
  createdAt: {
    type: Date,
    default: Date.now
  }

});

// Index on email for faster lookup performance during login
UserSchema.index({ email: 1 });

module.exports = mongoose.model('User', UserSchema);