/**
 * User Model - FaceGate Authentication System
 * Author: [Your Name] - Database Engineer
 * Date: April 2026
 * 
 * This model defines the schema for storing user registration data
 * including facial descriptors for passwordless biometric authentication.
 * 
 * Security Note: Raw face images are NEVER stored. Only 128-dimensional
 * float descriptor arrays are persisted to protect user biometric privacy.
 */

const mongoose = require('mongoose');

/**
 * @typedef {Object} UserSchema
 * @property {string} name - Full name of the registered user
 * @property {string} email - Unique email address (used as identity key)
 * @property {string} role - User role: 'admin' or 'user'
 * @property {number[]} faceDescriptor - 128-float facial encoding array
 * @property {Date} createdAt - Timestamp of registration
 */
const UserSchema = new mongoose.Schema({
  // Full name of the user
  name: {
    type: String,
    trim: true
  },

  // Email address - enforced unique to prevent duplicate identities
  email: {
    type: String,
    unique: true,
    lowercase: true,
    trim: true
  },

  // Role-based access control: admin gets full access, user gets dashboard
  role: {
    type: String,
    enum: ['admin', 'user'],
    default: 'user'
  },

  /**
   * Face Descriptor Array
   * 
   * This is the core biometric identifier.
   * Generated by face-api.js using the FaceRecognitionNet model.
   * Contains 128 float values representing unique facial features.
   * 
   * Security: This cannot be reverse-engineered back into a face image.
   * It is a one-way mathematical representation of facial geometry.
   */
  faceDescriptor: {
    type: [Number],
    validate: {
      validator: function(arr) {
        // Must have exactly 128 values for valid face descriptor
        return arr && arr.length === 128;
      },
      message: 'Face descriptor must contain exactly 128 float values'
    }
  },

  // Registration timestamp - useful for audit logs
  createdAt: {
    type: Date,
    default: Date.now
  }
});

// Index on email for fast lookup during login
UserSchema.index({ email: 1 });

// Export the model
module.exports = mongoose.model('User', UserSchema);